name: Java CI with Maven and Security Scans

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults: # Optional: set default working directory for all steps in this job
      run:
        working-directory: simple-token-validator

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        # Note: Maven cache might behave better if pom.xml is at root, or needs careful config.
        # For this setup, it should still mostly work.

    - name: Build with Maven
      run: mvn -B package # No need for --file if working-directory is set
      # Or explicitly:
      # working-directory: simple-token-validator
      # run: mvn -B package --file pom.xml

    - name: Run SpotBugs (SAST)
      run: mvn -B spotbugs:check
      # Or explicitly:
      # working-directory: simple-token-validator
      # run: mvn -B spotbugs:check --file pom.xml

    - name: Run OWASP Dependency-Check (SCA)
      run: mvn -B org.owasp:dependency-check-maven:check
      # Or explicitly:
      # working-directory: simple-token-validator
      # run: mvn -B org.owasp:dependency-check-maven:check --file pom.xml

    - name: Upload SpotBugs report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: spotbugs-report
        path: simple-token-validator/target/spotbugsXml.xml # Path is relative to repo root

    - name: Upload Dependency-Check report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: simple-token-validator/target/dependency-check-report.html # Path is relative to repo root
